name: develope

on:
  push:
    branches: [ developments ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Mavenを使ってビルド
      run: mvn --batch-mode --update-snapshots verify
    - name: リリースするディレクトリを作成
      run: mkdir staging && cp target/*.jar staging
    - name: パッケージをビルドの成果物としてアップロード
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
